services:
  - type: web
    name: horror-stories-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: horror-stories-db
          property: connectionString

databases:
  - name: horror-stories-db
    plan: starter
    region: oregon
    databaseName: horror_stories
    user: horror_stories_user