# Define required modules for the project
modules = ["nodejs-20", "web", "postgresql-16"]

# Command to run the application locally
run = "npm run dev"

# Hidden files/folders to exclude from the UI
hidden = [".config", ".git", "generated-icon.png", "node_modules", "dist", ".env*"]

# Nix package channel for dependencies
[nix]
channel = "stable-24_05"

# Deployment configuration for Google Cloud Run
[deployment]
deploymentTarget = "cloudrun"
build = ["sh", "-c", "npm ci && npm run build"]
run = ["sh", "-c", "npm start"]

# Single port mapping for local development
[[ports]]
localPort = 3002
externalPort = 3002

# Environment variables for development
[env]
NODE_ENV = "development"
PORT = "3002"

# Workflows for different run scenarios
[workflows]
runButton = "Start Web Feedback App"

[[workflows.workflow]]
name = "Start Web Feedback App"
author = 40492995
mode = "sequential"
[[workflows.workflow.tasks]]
task = "shell.exec"
args = "bash -c 'npm install && npm run dev'"
waitForPort = 3002

[[workflows.workflow]]
name = "Build & Start App"
author = 40492995
mode = "sequential"
[[workflows.workflow.tasks]]
task = "shell.exec"
args = "bash -c 'npm ci && npm run build && npm start'"
waitForPort = 3002

[[workflows.workflow]]
name = "Initialize DB and Launch"
author = 40492995
mode = "sequential"
[[workflows.workflow.tasks]]
task = "shell.exec"
args = "bash -c 'npm install && npx tsx scripts/init-db.ts && npm run dev'"
waitForPort = 3002

[[workflows.workflow]]
name = "Production Build Test"
author = 40492995
mode = "sequential"
[[workflows.workflow.tasks]]
task = "shell.exec"
args = "bash -c 'npm ci && npm run lint && npm run type-check && npm run build'"